fix: debug planfile

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -73,8 +73,15 @@ jobs:
 
       - name: Terraform Plan
         id: plan
-        run: terraform plan -no-color -input=false -out planfile -var-file=${{ env.ENV }}.tfvars -out=planfile
+        run: terraform plan -no-color -input=false -var-file=${{ env.ENV }}.tfvars -out=planfile
         continue-on-error: true
+
+      - name: Check Planfile
+        run: |
+          if [ ! -f "planfile" ]; then
+            echo "Planfile not found!"
+            exit 1
+          fi
 
       - name: Hide Previous Comments
         uses: kanga333/comment-hider@master
